name: simple_bonfire
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  bonfire: ^2.10.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/objects/
    - assets/images/maps/
    - assets/images/charactors/
    - assets/images/ui/
  fonts:
    - family: DotGothic16
      fonts:
        - asset: assets/fonts/DotGothic16-Regular.ttf